//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeluxeOM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkUpdate_Validations
    {
        public int ID { get; set; }
        public int BatchId { get; set; }
        public string Type { get; set; }
        public string ValidationLevel { get; set; }
        public string FileName { get; set; }
        public string ColumnName { get; set; }
        public string ColumnValue { get; set; }
        public string ValidationMessage { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int KeyId { get; set; }
    }
}
